intros:
  - "Have I ever told you about the time when "
  - "... boy, this brings me back, "
  - "You know, when I was your age, "
  - "Whoo, boy, "
  - "You might not realize this, but "
  - "Oof, wow, okay, what was I talking about? Oh yeah, "
stories:
  - "there I was, back in 'nam... "
  - "your grandmum and I met at a disco dance party... "
  - "she just left me there, holding the bag, hahah... "
  - "... ... ... wait, what was I talking about again? Well, anyways... "
  - "I learned the amount of apples a man can fit inside him is just unbelieve, let me tell you... "
  - "you gotta try to impress the ladies, boy. You gotta try your hardest. They'll make it worth your while... "
  - "ol' Bobby never was one to mess around with live grenades, if you know what I mean... "
  - "we still don't know how the duck got in there or quite what it thought it was doing with that stuffed dolphin... "
  - "let's just say the story ends with me getting beaten with a set of jumper cables... "
  - "well, we was going at it, a bit less than a year before your mom was born, when all of a sudden this... thing... just pops up... "
  - "your mom used to strip right down to nothing at a moments notice, and then run around screaming she was the queen of france... "
combiners:
  - "you wouldn't believe what happened next! "
  - "and that's not all, "
  - "that's not even the best part, "
  - "wait, where was I? Oh yeah, "
  - "which reminds me, "
  - "and back when I was still a young whippersnapper like yourself, well, "
