intros:
  - "Have I ever told you about the time when "
  - "... boy, this brings me back, "
  - "You know, when I was your age, "
  - "Whoo, boy, "
  - "You might not realize this, but "
  - "Oof, wow, okay, what was I talking about? Oh yeah, "
stories:
  - "there I was, back in 'nam... "
  - "your grandmum and I met at a disco dance party... "
  - "she just left me there, holding the bag, hahah... "
  - "... ... ... wait, what was I talking about again? Well, anyways... "
  - "I learned the amount of apples a man can fit inside him is just unbelieve, let me tell you... "
  - "you gotta try to impress the ladies, boy. You gotta try your hardest. They'll make it worth your while... "
  - "ol' Bobby never was one to mess around with live grenades, if you know what I mean... "
  - "we still don't know how the duck got in there or quite what it thought it was doing with that stuffed dolphin... "
  - "let's just say the story ends with me getting beaten with a set of jumper cables... "
  - "well, we was going at it, a bit less than a year before your mom was born, when all of a sudden this... thing... just pops up... "
  - "your mom used to strip right down to nothing at a moments notice, and then run around screaming she was the queen of france... "
  - "we used to walk up hill, both ways! In the snow! And we'd have to jump over giant snowballs that rolled down the hills, and if they hit... man, would you bounce!..."
  - "I liked to go out now and again and stand on rather precarious looking railings until they collapsed underneath me..."
  - "I had a really terrible cup of coffee. Just terrible. Worst in the world. It was so bad..."
  - "did I ever tell you about the time I escaped from some not-quite-nazis? I know you kids nowadays are spoiled free movement and all that, but back then were limited to hexagonal guard avoidance!"
  - "we didn't always have this pokymans thing you kids are into nowadays. We had to go out and catch real rats, and throw 'em in a bucket to make 'em fight! ..."
  - "I once had a dream where I was a fishing ghost. It was really weird. I don't know about the ghost part, but I certainly would like to be fishing right now..."
  - "I went to feed the ducks, but accidentally brought along a bunch of poisoned bread. Oops! There was this big jerk duck that totally deserved to be poisoned, though..."
  - "I never will forget the night I made six robbers run, even though I didn't have a blackjack, knife, or gun. I proved myself a hero of a very high degree! I ran for home, and six of them came running after me..."
  - "I once took up birdwatching as a hobby. Got some nice pictures, but I decided if I was going to be spending my day looking for at tits, there were better ways to go about it..."
  - "a bunch of midgets once tried to steal my treasure. That's why grampy always makes sure to carry his shotgun around... never know when the midgets might come after your treasure..."
  - "that bastard Elmo actually thought he could beat me at a game of medicine roulette. Man, you should have seen the look on his face! I showed him what for..."
  - "I ran over a whole bunch of people in a bright red top of the line mobility scooter. Hmm... actually that might just have been a really good dream..."
  - "...huh... what?... Who throws a Zardoz head in the lake? I don't know, why don't you ask your grandma. Man, now I really want to go fishing..."
combiners:
  - "you wouldn't believe what happened next! "
  - "and that's not all, "
  - "that's not even the best part, "
  - "wait, where was I? Oh yeah, "
  - "which reminds me, "
  - "and back when I was still a young whippersnapper like yourself, well, "
