both:
  other:
    'then': []
    'next': []
    'while': []
    'about': []
    'and': []
    'or': []
    'want': []
    'do': []
    'I mean': []
    'to': []
    'please': []
    'help': []
    'are': []
    'done': []
    'work': []
    'something': []
    'nothing': []
    'happening': []
    'is': []
    'mean': []
  useful:
    'yes': []
    'no': []
    'uh': []
    'oh': []
    'sorry': []
    'ok': []
    'not': []
    'wait': []
  nouns:
    'anything': []
    'god': []
    'button': []
    'monitor': []
    'screen': []
    'button': []
    'knob': []
    'cable': []
    'plug': []
    'wall': []
    'outlet': []
    'logo': []
    'power': []
    'tower': []
    'circle': []
    'square': []
    'apple': []
    'orange': []
    'banana': []
    'grapes': []
    'zebra': []
    'key': []
    'desk': []
    'grandson': []
    'grandpa': []
    'pokemon': []
  relations:
    'on': []
    'front': []
    'back': []
    'first': []
    'second': []
    'third': []
    'left': []
    'right': []
    'bottom': []
    'top': []
    'up': []
    'down': []
    'in': []
    'out': []
    'after': []
    'before': []
  actions:
    'need': []
    'tell': []
    'do': []
    'touch': []
  'pronouns/articles':
    'I': []
    'you': []
    'we': []
    'it': []
    'that': []
    'this': []
    'those': []
    'these': []
    'the': []
    'a': []
    'an': []
    'some': []
  queries:
    'how': []
    'why': []
    'what': []
    'when': []
    'where': []
  punctuation:
    '?': []
    '.': []
    '!': []
    '...': []
    ',': []
  count:
    '': []
    '2': []
    '3': []
    '4': []
    '5': []
    '6': []
    '7': []
    '8': []
    '9': []
  properties:
    'many': []
    'good': []
    'bad': []
    'red': []
    'blue': []
    'green': []
    'white': []
    'black': []
    'yellow': []
    'purple': []
    'round': []
    'sharp': []
    'pointy': []
    'flat': []
    'square': []
  sounds:
    'beep': []
    'buzz': []
    'crack': []
    'pop': []
grandson:
  nouns:
    'button': ['depressor']
  relations:
  actions:
    'turn': []
    'press': []
    'take out': []
    'attach': []
    'change': []
    'switch': []
  technical:
    'degauss': []
    'mode': []
    'aux1': []
    'aux2': []
    'tv': []
  sounds:
grandpa:
  nouns:
    'button': ['button', 'button', 'doohickey']
    'monitor': ['box', 'tv', 'gidgit', 'computer', 'computer']
    'screen': ['window', 'tv', 'flat bit of the tv', 'flat bit of the computer']
    'knob': ['knob', 'knob', 'spinny bit', 'spinner', 'dial']
    'cable': ['cable', 'wire', 'plug', 'snakey thing', 'long bit']
    'plug': ['plug', 'cable', 'wire', 'knobby bit', 'whatchamacallit', 'doodad']
    'wall': ['wall']
    'outlet': ['outlet', 'plug', 'socket']
    'logo': ['logo', 'scribble', 'brand', 'gobblygook', 'label', 'sign']
    'tower': ['other thing', 'box', 'computer', 'other computer', 'other box', 'thingamabob', 'whatever that is', 'shelf']
    'circle': ['circle', 'circle', 'round thing', 'ball']
    'square': ['square', 'square', 'square thing']
    'pokemon': ['pokeyman', 'pokeymans', 'pikey mans', 'pocket mans', 'digimon', 'digimon', 'power rangers', 'dinosaurs', 'battle bugs', 'mario']
  relations:
  useful:
    'thing': []
    'whatchamacallit': []
    'forgot': []
  actions:
    'went': []
    'turned': []
    'pressed': []
    'took out': []
    'put in': []
    'changed': []
    'switched': []
  technical:
    'fuzzed up': []
    'fizzed over': []
    'all wacky': []
  sounds:
    'zap': []
    'buzz': []
