both:
  other:
    'then': []
    'next': []
    'while': []
    'about': []
    'and': []
    'or': []
    'want': []
    'do': []
    'I mean': []
    'to': []
    'please': []
    'are': []
    'done': []
    'work': []
    'something': []
    'nothing': []
    'happening': []
    'is': []
    'mean': []
    'now': []
    'hello': []
    'same': []
    'different': []
  useful:
    'yes': []
    'no': []
    'uh': []
    'oh': []
    'sorry': []
    'ok': []
    'not': []
    'wait': []
  nouns:
    'color': []
    'anything': []
    'god': []
    'button': []
    'monitor': []
    'screen': []
    'knob': []
    'cable': []
    'plug': []
    'wall': []
    'outlet': []
    'logo': []
    'power': []
    'tower': []
    'circle': []
    'square': []
    'apple': []
    'orange': []
    'banana': []
    'grapes': []
    'zebra': []
    'key': []
    'desk': []
    'grandson': []
    'grandpa': []
    'pokemon': []
    'signal': []
    'switch': []
  relations:
    'on': []
    'front': []
    'back': []
    'first': []
    'second': []
    'third': []
    'left': []
    'right': []
    'bottom': []
    'top': []
    'up': []
    'down': []
    'in': []
    'out': []
    'after': []
    'before': []
  actions:
    'need': []
    'tell': []
    'do': []
    'touch': []
    'help': []
  'pronouns/articles':
    'I': []
    'you': []
    'we': []
    'it': []
    'that': []
    'this': []
    'those': []
    'these': []
    'the': []
    'a': []
    'an': []
    'some': []
    'my': []
    'your': []
  queries:
    'how': []
    'why': []
    'what': []
    'when': []
    'where': []
    'has': []
  punctuation:
    '?': []
    '.': []
    '!': []
    '...': []
    ',': []
  count:
    '1': []
    '2': []
    '3': []
    '4': []
    '5': []
    '6': []
    '7': []
    '8': []
    '9': []
  properties:
    'many': []
    'good': []
    'bad': []
    'red': []
    'blue': []
    'green': []
    'white': []
    'black': []
    'yellow': []
    'purple': []
    'round': []
    'sharp': []
    'pointy': []
    'flat': []
    'square': []
    'important': []
  sounds:
    'beep': []
    'buzz': []
    'crack': []
    'pop': []
grandson:
  nouns:
    'button': ['depressor', 'key', 'control', 'switch']
    'port': ['anchorage', 'dock', 'gate', 'harbor']
    'switch': ['lever', 'exchanger', 'transformice', 'shifter', 'swapper']
    'god': ['deity', 'goddess', 'gods']
    'monitor': ['televiewer', 'scrutinizer', 'observation crate']
    'screen': ['view window', 'lattice', 'mesh']
    'knob': ['dial', 'valve']
    'cable': ['coaxial', 'link']
    'plug': ['male bit', 'stopper', 'wedge']
    'outlet': ['female bit', 'porthole', 'inlet']
    'logo': ['brand', 'mark']
    'power': ['activation', 'potential', 'active', 'dynamism']
    'tower': ['mount box', 'casing', 'housing']
    'apple': ['red fruit', 'red delicious', 'granny smith', 'sour apple']
    'orange': ['clementine', 'ugli fruit', 'grapefruit']
    'banana': ['cavandish', 'plantain']
    'zebra': ['striped equine']
    'key': ['button', 'unlocker', 'mapper']
    'desk': ['table']
    'grandson': []
    'grandpa': ['grandpappy', 'poppy', 'grampaw', 'gramps']
    'pokemon': ['pocket monsters']
  relations:
  actions:
    'turn': ['rotate', 'flip', 'modulate']
    'press': ['depress', 'toggle', 'activate', 'push']
    'take out': ['remove', 'detach', 'disassemble', 'disocciate']
    'put in': ['adhere', 'associate', 'entangle', 'affix']
    'change': ['adjust', 'revolve', 'transform', 'modulate', 'switch', 'swap']
  technical:
    'degauss': ['recalibrate', 'flaggelate']
    'mode': ['type', 'op']
    'aux1': ['zeal', 'flel', 'doop3']
    'aux2': ['znak', 'durop', 'loodle2']
    'tv': ['game', 'mix']
  properties:
    'good': ['excellent', 'rad', 'tubular', 'gnarly', 'phat', 'sweet', 'smashing', 'wicked']
    'bad': ['gnarly', 'terrible', 'dumb', 'grody', 'nasty', 'sucky']
  sounds:
  other:
grandpa:
  nouns:
    'button': ['doohickey', 'thingamabob', 'switch', 'circle']
    'monitor': ['box', 'tv', 'tv', 'gidgit', 'computer', 'computer']
    'screen': ['window', 'tv', 'flat bit of the tv', 'flat bit of the computer', 'glass']
    'knob': ['knob', 'spinny bit', 'spinner', 'dial']
    'cable': ['wire', 'plug', 'snakey thing', 'long bit']
    'plug': ['cable', 'wire', 'knobby bit', 'whatchamacallit', 'doodad']
    'outlet': ['outlet', 'plug', 'socket']
    'logo': ['logo', 'scribble', 'brand', 'gobblygook', 'label', 'sign']
    'tower': ['other thing', 'box', 'computer', 'other computer', 'other box', 'thingamabob', 'whatever that is', 'shelf']
    'circle': ['circle', 'circle', 'round thing', 'ball']
    'square': ['square', 'square', 'square thing']
    'pokemon': ['pokeyman', 'pokeymans', 'pikey mans', 'pocket mans', 'digimon', 'digimon', 'power rangers', 'dinosaurs', 'battle bugs', 'mario']
  relations:
  useful:
    'thing': []
    'whatchamacallit': []
    'forgot': []
  actions:
    'went': []
    'turned': []
    'pressed': []
    'took out': []
    'put in': []
    'changed': []
    'switched': []
  technical:
    'fuzzed up': []
    'fizzed over': []
    'all wacky': []
  sounds:
    'zap': []
    'buzz': []
