both:
  pronouns:
    'I': []
    'you': []
    'we': []
    'it': []
    'that': []
    'this': []
    'those': []
    'these': []
  other:
    'yes': []
    'no': []
    '... uh': []
    '... I mean': []
grandson:
  nouns:
    'button': ['depressor']
grandpa:
  nouns:
    'button': ['whatchamacallit']
